#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/guid" ] || [ -e "/etc/init/guid.conf" ]; then
	if [ ! -e "/etc/init/guid.conf" ]; then
		update-rc.d guid defaults >/dev/null
	fi
	invoke-rc.d guid start || exit $?
fi
# End automatically added section
